name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/original-repo.git
          git fetch upstream
          git merge upstream/main --no-edit || true
          git push origin main
